modLoader="lowcodefml"
loaderVersion="*"
license="MIT"
[[mods]]
    modId="tinkers_shovels"
    version="1.0.0"
    displayName="Tinkers' Shovels"
    authors="OOrreeooss"
    description='''A Thing Pack for Tinkers' Construct that adds shovels.'''
[[dependencies.tinkers_shovels]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.10.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_shovels]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
