modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/OOrreeooss/TinkersShovels/issues"
license="MIT"
[[mods]]
    modId="tinkers_shovels"
    version="1.0.1"
    displayName="Tinkers' Shovels"
    authors="OOrreeooss"
    description='''A thingpack for Tinkers' Construct that adds shovels.'''
[[dependencies.tinkers_shovels]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.10.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_shovels]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
